import { ProviderId, ProviderAdapter } from "../types";

export abstract class BaseProviderAdapter implements ProviderAdapter {
  abstract id: ProviderId;
  abstract name: string;

  /**
   * Concrete implementations must override this method.
   * This method should return the raw JSON string generated by the LLM.
   */
  abstract generateJSON(prompt: string, modelId: string): Promise<string>;

  /**
   * Concrete implementations must override this to check for environment variables.
   */
  abstract isAvailable(): boolean;

  /**
   * Utility to safely extract JSON from markdown blocks if the LLM
   * disobeys JSON mode and wraps the response in ```json ... ```
   */
  protected extractJSON(text: string): string {
    const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
    if (jsonMatch && jsonMatch[1]) {
      return jsonMatch[1].trim();
    }
    return text.trim();
  }
}
